### ISSUE TITLE
Send email when list is shared

### ISSUE THREAD

**Issue by cundejo** [cundejo/tadeas#39]
Send an email notifying the person that someone shared a list with them.

**Comment by cundejo** [comment]
@aleirim can you please give me a template with the content that the email should have?

**Comment by aleirim** [comment]
@cundejo We could use this as a first draft and refine it later.

draft 1:
Hi [email],

[email of the user sharing a list] has invited you to use Tadeas to access the to-do lists shared with you, and create your own. Get started by [setting up your account | signing up] using this link: [tadeas.app].

Tadeas is a free, simple to-do list app to organize your day and share tasks with others. 

[Enjoy | Welcome aboard | We look forward to having you join us], 
The Tadeas Team 

P.S. Need help getting started? Need to know more about Tadeas? Check out our help [documentation].

draft 2:
Hi [email],

[email of the user sharing a list] has shared a to-do list with you using Tadeas.  To access this list, get started by [setting up your account | signing up] using this link: [tadeas.app].

Tadeas is a free, simple to-do list app to organize your day and share tasks with others.  

[Enjoy | Welcome aboard | We look forward to having you join us],  
The Tadeas Team 

P.S. Need help getting started? Need to know more about Tadeas? Check out our help [documentation].


Also, is pretty common to include something like: 
Note: This email was intended for [email address]. If you weren't expecting ...., you can ignore this email.

But it's completely optional.

**Comment by aleirim** [comment]
we should create a help page and include basic functionalities while stating the product's advantages:
- completely free
- no password is required
- share lists
- manage completed tasks
- how to rename, share, create, and delete lists
- how to modify tasks
- how to revoke access to a shared list

what do you think? we could include this link in the previous email.

**Comment by cundejo** [comment]
> 

@aleirim I agree on mentioning the functionalities part, but not in the how-to's, all the features are small enough, they don't need an explanation

As I see it we have 2 options here: 
- Include a section in the about page
- Create a Help page as you mentioned

I'm comfortable with any, create another task for that.
